name: CI - Build & Test
on: [push, pull_request]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout code
            uses: actions/checkout@v4

        -   name: Build Docker image
            run: docker build -t mydevops-app ./week2-app

        -   name: Run container
            run: docker run -d -p 5000:5000 --name ci-test mydevops-app

        -   name: Wait for startup
            run: sleep 3

        -   name: Health check
            run: curl -f http://localhost:5000/health || exit

        -   name: Cleanup
            if: always()
            run: docker stop ci-test && docker rm ci-test

